### ISSUE TITLE
finds nothing

### ISSUE THREAD

**Issue by tatsujb** [Ivshti/stremio-local-files#6]
you don't specify what formatting to give.

what specific folder stremieo will be looking in and what formatting it will accept.

what if I just want to open any old file?

using ubuntu 18.04 here.

**Comment by Ivshti** [comment]
It will accept formats defined in this module: https://github.com/Ivshti/video-name-parser

"any file" can be opened via just dragging and dropping it on stremio

**Comment by jaruba** [comment]
@tatsujb 

As for the statement that it finds nothing, I believe that it is related to this PR https://github.com/Ivshti/stremio-local-files/pull/5

We are currently working on a fix for it.
